In [3]:
import numpy as np

#read data from text files
with open('data/reviews.txt') as f:
    reviews = f.read()

with open('data/labels.txt') as f:
    labels = f.read()

In [4]:
print(reviews[:2000])
print()
print(labels[:20])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

In [7]:
#removing all punctuations

from string import punctuation
print(punctuation)

reviews = reviews.lower()
all_text = ''.join(c for c in reviews if c not in punctuation)
print(all_text[:200])

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life  such as  teachers   my   years in the teaching profession lead me to believe that bromwell high  s 


In [8]:
#split by new lines and spaces
reviews_split = all_text.split('\n')
all_text = ''.join(reviews_split)

#create a list of words
words = all_text.split()

In [9]:
words[:30]

['bromwell',
 'high',
 'is',
 'a',
 'cartoon',
 'comedy',
 'it',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'teachers',
 'my',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me']

In [63]:
from collections import Counter 

counts = Counter(words) #How many times does a word appear in our text
vocab = sorted(counts, key= counts.get, reverse=True) #sorting each word according to their occurance
#we want to start encoding with 1, so the most common words like 'the' or 'a' should be encoded first as 1
vocab_to_int = {word: ii for ii, word in enumerate(vocab,1)}

# print(vocab_to_int)

reviews_ints = []
for review in reviews_split:
    reviews_ints.append([vocab_to_int[word] for word in review.split()])

In [64]:
print('Unique Words: ', len(vocab_to_int))
print()

print('Tokenised reviews: \n', reviews_ints[:1])

Unique Words:  74072

Tokenised reviews: 
 [[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23]]


In [65]:
labels_split = labels.split('\n')
encoded_label = np.array([1 if label == 'positive' else 0 for label in labels_split])

In [66]:
print(encoded_label[:20])

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]


In [67]:
#checking for zero-length reviews or too long reviews
review_len = Counter([len(x) for x in reviews_ints])
print('zero length reviews', review_len['0'])
print('Maximum lenght reviews', max(review_len))

zero length reviews 0
Maximum lenght reviews 2514


In [68]:
type(reviews_ints)
# print(reviews_ints)

list

In [69]:
print("Number of reviews before removing outliers: ", len(reviews_ints))

#index of non zero length reviews
non_zero_idx = [ii for ii, review in enumerate(
    reviews_ints) if len(review) != 0]

reviews_ints = [reviews_ints[ii] for ii in non_zero_idx]
encoded_label = np.array([encoded_label[ii] for ii in non_zero_idx])

print('Number of reviews after removing outliers: ', len(reviews_ints))


Number of reviews before removing outliers:  25001
Number of reviews after removing outliers:  25000


In [76]:
def pad_features(reviews_ints, seq_length):
    features = np.zeros((len(reviews_ints), seq_length),dtype = int)

    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] =   np.array(row)[:seq_length] #keeping zeros in front

    return features

In [77]:
seq_length = 200

features = pad_features(review_ints, seq_length)

## test statements - do not change - ##
assert len(features) == len(review_ints), "Your features should have as many rows as reviews."
assert len(features[0]) == seq_length, "Each feature row should contain seq_length values."

#print first 10 values of first 30 batches
print(features[:30,:10])

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22382    42 46418    15   706 17139  3389    47    77    35]
 [ 4505   505    15     3  3342   162  8312  1652     6  4819]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   54    10    14   116    60   798   552    71   364     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   330   578    34     3   162   748  2731     9   325]
 [    9    11 10171  5305  1946   689   444    22   280   673]
 [    0     0     0     0     0     0     0     0     0

In [86]:
split_frac = 0.8 #can be 0.9 too

#training, test and validation data split

split_idx = int(len(features)*0.8)
train_x , remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_label[:split_idx], features[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

print('\t\t\tFeatures Shapes')
print("Train set: \t\t", train_x.shape, "\nValidation set: \t",
      val_x.shape, "\nTest set: \t\t", test_x.shape)


			Features Shapes
Train set: 		 (20000, 200) 
Validation set: 	 (2500, 200) 
Test set: 		 (2500, 200)
